import {StyleSheet} from 'react-native';

export const detailCss = StyleSheet.create({
  container: {
    flex: 1,
  },
  scroll: {
    backgroundColor: 'white',
  },
  contWrap1: {
    width: '100%',
    alignItems: 'center',
  },
  backWrap: {
    width: '92%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'absolute',
    marginTop: 15,
    zIndex: 15,
  },
  shadowimg: {
    position: 'absolute',
    zIndex: 10,
    width: '100%',
    borderRadius: 15,
  },
  profileimg: {
    width: '100%',
    borderRadius: 15,
  },
  contWrap2: {
    width: '100%',
    marginLeft: 20,
  },
  descTitle: {
    marginTop: 7,
    marginBottom: 7,
    fontWeight: '500',
    fontSize: 18,
    color: '#111111',
  },
  descWrap: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  desc: {
    marginRight: 9,
    marginBottom: 6,
  },
  descFont: {
    fontSize: 15,
    fontWeight: '400',
    color: '#111111',
  },
  contWrap3: {
    width: '100%',
    marginLeft: 16,
    backgroundColor: 'white',
  },
  cateFont1: {
    fontSize: 12,
    fontWeight: '500',
    color: '#F84B62',
    marginRight: 4,
    backgroundColor: '#F84B621A',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
  },
  cateFont2: {
    fontSize: 13,
    fontWeight: '400',
    color: '#111111',
    marginRight: 4,
    backgroundColor: '#F2F2F2',
    paddingHorizontal: 5,
    paddingVertical: 3,
    borderRadius: 12,
  },
  contWrap4: {
    width: '100%',
    paddingTop: 12,
    paddingLeft: 16,
    paddingBottom: 12,
    borderColor: '#E6E6E6',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    flexDirection: 'row',
    backgroundColor: 'white',
  },
  smallimg: {
    borderRadius: 3,
  },
  introWrap: {
    marginLeft: 10,
  },
  introTitle: {
    fontWeight: '500',
    fontSize: 13,
    color: '#111111',
  },
  introTextwrap: {
    flexDirection: 'row',
    marginVertical: 2,
  },
  introText: {
    width: 47,
    height: 18,
    fontWeight: '400',
    color: '#888888',
    fontSize: 10,
    textAlign: 'center',
    textAlignVertical: 'center',
    marginRight: 4,
    paddingHorizontal: 2,
    backgroundColor: '#F2F2F2',
    borderRadius: 12,
  },
  introReview: {
    flexDirection: 'row',
    // textAlignVertical: 'center',
  },
  fontReview: {
    fontWeight: '400',
    color: '#888888',
    fontSize: 10,
    alignItems: 'center',
  },
  introScore: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 15,
  },
  scoreImg: {
    marginRight: 4,
  },
  contWrap5: {
    width: '100%',
    marginLeft: 16,
  },
  icon_wrap: {
    position: 'absolute',
    zIndex: 99,
    flexDirection: 'row',
    alignItems: 'center',
  },
  king_icon: {
    top: 3,
    left: 13,
  },
  hot_icon: {
    top: 11,
    left: 18,
  },
  smallProfileWrap: {
    marginTop: 11,
    marginBottom: 13,
    flexDirection: 'row',
    alignItems: 'center',
    textAlign: 'center',
  },
  smallProfile: {
    borderRadius: 45,
    marginRight: 8,
    backgroundColor: '#F2F2F2',
  },
  inviteButton: {
    marginRight: 32,
    height: 48,
    backgroundColor: '#F84B62',
    borderRadius: 8,
  },
  inviteText: {
    textAlign: 'center',
    marginVertical: 13,
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '500',
  },
  thunderContentsWrap: {
    marginLeft: 4,
    marginRight: 36,
    marginVertical: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 2,
    borderColor: '#0000001A',
  },
  thunderContents: {
    fontSize: 15,
    fontWeight: '400',
    color: '#111111',
    lineHeight: 22,
  },
  contWrap6: {
    width: '100%',
  },
  foodImageWrap: {
    marginHorizontal: 16,
    alignItems: 'center',
  },
  foodImage: {
    width: '100%',
    borderRadius: 15,
    marginBottom: 8,
  },
  contWrap7: {
    marginLeft: 16,
  },
  comment_title: {
    fontSize: 18,
    fontWeight: '500',
    lineHeight: 22,
    color: '#111111',
  },
  comment_zone: {
    flexDirection: 'row',
    marginTop: 15,
    marginBottom: 70,
    alignItems: 'center',
    // backgroundColor: 'pink',
  },
  comment_input: {
    width: 250,
    maxHeight: 130,
    marginTop: 10,
    marginRight: 34,
    // borderWidth: 1,
    padding: 10,
  },
  comment_btn: {
    fontSize: 15,
    fontWeight: '700',
    color: '#00000066',
    // backgroundColor: 'pink',
  },
  buttonB: {
    width: '100%',
    height: 56,
    backgroundColor: '#F84B62',
  },
  buttonT: {
    textAlign: 'center',
    marginVertical: 17,
    color: '#FFFFFF',
    fontSize: 15,
  },
});
